### PR TITLE
Compress Nobel prize example GIFs

### PR DESCRIPTION
**Pull request by flother**
I had a go at reducing the size of the GIFs down using [Optimage](https://optimage.app/)'s visually-lossless compression, and got the images down to ~1.5 MB each — around a 74% reduction:

- `marie-heavy.gif` from 5.21 MB to 1.24 MB
- `radium-heavy.gif` from 6.71 to 1.61 MB

As far as I can tell, Optimage has kept its promise and there's no perceptual difference between old and new images. I'm not sure if this is enough of a reduction to get the repo into a codesandbox, but it should at least help fix meilisearch/meilisearch-vue#34.

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @flother! thanks for your PR!
@bidoubiwa will review your PR once she comes back from vacation. She's the maintainer of this repo :)

**Comment by bidoubiwa** [comment]
Thanks a lot for this optimization ! 🔥

**Review by bidoubiwa — APPROVED** [review]
Thanks a lot for this optimization ! 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
